- activity: 2E
  date: Aug 28, 2022
- activity: 3E
  date: Aug 29, 2022
- activity: 2E
  date: Sep 1, 2022
- activity: 3E
  date: Sep 2, 2022
- activity: Crosstrain
  date: Sep 4, 2022
- activity: 1E
  date: Sep 5, 2022
- activity: 4L
  date: Sep 8, 2022
- activity: 5x(3:00 T + 2:00 W)
  date: Sep 10, 2022
- activity: 3E + 6ST
  date: Sep 11, 2022
- activity: 3E
  date: Sep 12, 2022
- activity: 8x(0.15 R + 0.15 jg)
  date: Sep 13, 2022
- activity: 3E XC
  date: Sep 15, 2022
- activity: 5L
  date: Sep 16, 2022
- activity: Crosstrain
  date: Sep 17, 2022
- activity: 2E
  date: Sep 18, 2022
- activity: 4x(5:00 T + 1:00 jg)
  date: Sep 19, 2022
- activity: 4E XC
  date: Sep 20, 2022
- activity: 3E
  date: Sep 22, 2022
- activity: 8x(0.15 R + 0.15 jg)
  date: Sep 23, 2022
- activity: 3E
  date: Sep 24, 2022
- activity: 5L XC
  date: Sep 25, 2022
- activity: 3E
  date: Sep 26, 2022
- activity: 2x(1 T + 2:00 jg)
  date: Sep 27, 2022
- activity: 4E
  date: Sep 29, 2022
- activity: Shake-out
  date: Sep 30, 2022
- activity: 4E
  date: Feb 13, 2023
- activity: 4.5E
  date: Feb 15, 2023
- activity: 4E-T
  date: Feb 17, 2023
- activity: 5L
  date: Feb 19, 2023
- activity: 4E + 10ST
  date: Feb 20, 2023
- activity: 4E-T
  date: Feb 21, 2023
- activity: 4E + 10ST
  date: Feb 23, 2023
- activity: 4E
  date: Feb 24, 2023
- activity: 6L E-T
  date: Feb 26, 2023
- activity: 4E + 10ST
  date: Feb 28, 2023
- activity: 4E XC
  date: Mar 1, 2023
- activity: 4E-T
  date: Mar 2, 2023
- activity: 4E + 10ST
  date: Mar 4, 2023
- activity: 7L E-T-E
  date: Mar 5, 2023
- activity: 5E-T
  date: Mar 7, 2023
- activity: 8x 200R / 200jg
  date: Mar 8, 2023
- activity: 5E
  date: Mar 9, 2023
- activity: 2x 1T / 1:00w
  date: Mar 10, 2023
- activity: 4E
  date: Mar 12, 2023
- activity: 10k TT / 7L
  date: Mar 13, 2023
- activity: 10x 200R / 200jg
  date: Mar 15, 2023
- activity: 5E XC
  date: Mar 16, 2023
- activity: 4x 6:00T / 1:00w
  date: Mar 17, 2023
- activity: 5E
  date: Mar 18, 2023
- activity: 8L XC last 3T
  date: Mar 20, 2023
- activity: 5E
  date: Mar 21, 2023
- activity: 8x 300R / 300E
  date: Mar 22, 2023
- activity: 5.5E XC
  date: Mar 23, 2023
- activity: 5E
  date: Mar 24, 2023
- activity: 3x 1T / 1:00w
  date: Mar 25, 2023
- activity: 8.5L XC last 3T
  date: Mar 27, 2023
- activity: 5E
  date: Mar 28, 2023
- activity: 6x 3:00H / 2:00E
  date: Mar 29, 2023
- activity: 5E
  date: Mar 30, 2023
- activity: 3x 1T / 1:00w
  date: Mar 31, 2023
- activity: 5E
  date: Apr 1, 2023
- activity: 9L 3E-3M-3HM
  date: Apr 3, 2023
- activity: 5E XC
  date: Apr 4, 2023
- activity: 6x 3:00H / 2:00jg
  date: Apr 5, 2023
- activity: 3x 1T / 1:00w
  date: Apr 7, 2023
- activity: 5E
  date: Apr 8, 2023
- activity: 9L 3E-3M-3HM
  date: Apr 9, 2023
- activity: 5E XC
  date: Apr 10, 2023
- activity: 5E
  date: Apr 11, 2023
- activity: 5x 5:00T / 1:00w
  date: Apr 12, 2023
- activity: 4E
  date: Apr 13, 2023
- activity: 2E
  date: Apr 14, 2023
